include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.pb.dart"
    - "**/*.pbenum.dart"
    - "**/*.pbgrpc.dart"
    - "**/*.pbjson.dart"
