module.exports = {
  disableEmoji: false,
  // format: "{type}{scope}: {emoji}{subject}",
  format: "{emoji}{type}: {subject}",
  list: [
    "feat",
    "fix",
    "test",
    "chore",
    "upgrade",
    "refactor",
    "docs",
    "style",
    "ci",
    "perf",
    "release",
  ],
  maxMessageLength: 64,
  minMessageLength: 3,
  // questions: ["type", "scope", "subject", "body", "breaking", "issues", "lerna"],
  questions: ["type", "subject", "body", "breaking", "issues", "lerna"],
  // scopes: [],
  types: {
    feat: {
      description: "新しい機能",
      emoji: "🚀",
      value: "feat",
    },
    fix: {
      description: "バグの修正",
      emoji: "🐛",
      value: "fix",
    },
    test: {
      description: "テストの追加",
      emoji: "💚",
      value: "test",
    },
    refactor: {
      description: "リファクタリング",
      emoji: "💡",
      value: "refactor",
    },
    chore: {
      description: "ツール関連の変更",
      emoji: "🔧",
      value: "chore",
    },
    upgrade: {
      description: "SDKやライブラリのバージョンアップ",
      emoji: "📦️",
      value: "upgrade",
    },
    docs: {
      description: "ドキュメントのみの変更",
      emoji: "📝",
      value: "docs",
    },
    style: {
      description: "フォーマットのみの変更",
      emoji: "✨",
      value: "style",
    },
    ci: {
      description: "CI 関連の変更",
      emoji: "🤖",
      value: "ci",
    },
    perf: {
      description: "パフォーマンス向上の変更",
      emoji: "⚡️",
      value: "perf",
    },
    release: {
      description: "リリースコミットの作成",
      emoji: "🎉",
      value: "release",
    },
    messages: {
      type: "Select the type of change that you're committing:",
      // customScope: "Select the scope this component affects:",
      subject: "Write a short, imperative mood description of the change:\n",
      body: "Provide a longer description of the change:\n ",
      breaking: "List any breaking changes:\n",
      footer: "Issues this commit closes, e.g #123:",
      confirmCommit: "The packages that this commit has affected\n",
    },
  },
};
