version: "3.8"
services:
    common:
      container_name: ebisuiru-fc-common
      build:
        context: .
        dockerfile: ./Dockerfile
      # tty: true
      volumes:
        - .:/ebisuiru-fc-common
      command: make grpc
