// 参考
// https://zenn.dev/hsaki/books/golang-grpc-starting/viewer/proto
// https://dev.classmethod.jp/articles/golang-grpc-sample-project/
//

// protoのバージョンです。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: a8/v1/a8.proto

// メッセージ型などの名前の衝突を避けるためにパッケージ名を指定します。

package a8v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitA8Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode string `protobuf:"bytes,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Body       string `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *SubmitA8Response) Reset() {
	*x = SubmitA8Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_a8_v1_a8_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitA8Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitA8Response) ProtoMessage() {}

func (x *SubmitA8Response) ProtoReflect() protoreflect.Message {
	mi := &file_a8_v1_a8_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitA8Response.ProtoReflect.Descriptor instead.
func (*SubmitA8Response) Descriptor() ([]byte, []int) {
	return file_a8_v1_a8_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitA8Response) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *SubmitA8Response) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type SubmitA8Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *SubmitA8Request) Reset() {
	*x = SubmitA8Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_a8_v1_a8_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitA8Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitA8Request) ProtoMessage() {}

func (x *SubmitA8Request) ProtoReflect() protoreflect.Message {
	mi := &file_a8_v1_a8_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitA8Request.ProtoReflect.Descriptor instead.
func (*SubmitA8Request) Descriptor() ([]byte, []int) {
	return file_a8_v1_a8_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitA8Request) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_a8_v1_a8_proto protoreflect.FileDescriptor

var file_a8_v1_a8_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x61, 0x38, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x38, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x61, 0x38, 0x2e, 0x76, 0x31, 0x22, 0x46, 0x0a, 0x10, 0x53, 0x75, 0x62, 0x6d, 0x69,
	0x74, 0x41, 0x38, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62,
	0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22,
	0x23, 0x0a, 0x0f, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x41, 0x38, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x72, 0x6c, 0x32, 0x48, 0x0a, 0x09, 0x41, 0x38, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x3b, 0x0a, 0x08, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x41, 0x38, 0x12, 0x16, 0x2e,
	0x61, 0x38, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x41, 0x38, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x61, 0x38, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x75,
	0x62, 0x6d, 0x69, 0x74, 0x41, 0x38, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2f,
	0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x31, 0x30, 0x6b,
	0x6e, 0x2f, 0x77, 0x69, 0x6e, 0x6b, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2f, 0x61, 0x38, 0x2f, 0x76, 0x31, 0x3b, 0x61, 0x38, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_a8_v1_a8_proto_rawDescOnce sync.Once
	file_a8_v1_a8_proto_rawDescData = file_a8_v1_a8_proto_rawDesc
)

func file_a8_v1_a8_proto_rawDescGZIP() []byte {
	file_a8_v1_a8_proto_rawDescOnce.Do(func() {
		file_a8_v1_a8_proto_rawDescData = protoimpl.X.CompressGZIP(file_a8_v1_a8_proto_rawDescData)
	})
	return file_a8_v1_a8_proto_rawDescData
}

var file_a8_v1_a8_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_a8_v1_a8_proto_goTypes = []interface{}{
	(*SubmitA8Response)(nil), // 0: a8.v1.SubmitA8Response
	(*SubmitA8Request)(nil),  // 1: a8.v1.SubmitA8Request
}
var file_a8_v1_a8_proto_depIdxs = []int32{
	1, // 0: a8.v1.A8Service.SubmitA8:input_type -> a8.v1.SubmitA8Request
	0, // 1: a8.v1.A8Service.SubmitA8:output_type -> a8.v1.SubmitA8Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_a8_v1_a8_proto_init() }
func file_a8_v1_a8_proto_init() {
	if File_a8_v1_a8_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_a8_v1_a8_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitA8Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_a8_v1_a8_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitA8Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_a8_v1_a8_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_a8_v1_a8_proto_goTypes,
		DependencyIndexes: file_a8_v1_a8_proto_depIdxs,
		MessageInfos:      file_a8_v1_a8_proto_msgTypes,
	}.Build()
	File_a8_v1_a8_proto = out.File
	file_a8_v1_a8_proto_rawDesc = nil
	file_a8_v1_a8_proto_goTypes = nil
	file_a8_v1_a8_proto_depIdxs = nil
}
