// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: user_profile/v1/user_profile.proto

package userprofilev1connect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	v1 "github.com/gisucoinc/ebisuiru-fc-common/server/user_profile/v1"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// UserProfileServiceName is the fully-qualified name of the UserProfileService service.
	UserProfileServiceName = "userprofile.v1.UserProfileService"
)

// UserProfileServiceClient is a client for the userprofile.v1.UserProfileService service.
type UserProfileServiceClient interface {
	GetUserProfile(context.Context, *connect_go.Request[v1.GetUserProfileRequest]) (*connect_go.Response[v1.GetUserProfileResponse], error)
	UpdateUserProfile(context.Context, *connect_go.Request[v1.UpdateUserProfileRequest]) (*connect_go.Response[emptypb.Empty], error)
	GetOwnUserProfile(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetOwnUserProfileResponse], error)
	GetAdminUserProfile(context.Context, *connect_go.Request[v1.GetAdminUserProfileRequest]) (*connect_go.Response[v1.GetAdminUserProfileResponse], error)
	SearchAdminUserProfiles(context.Context, *connect_go.Request[v1.SearchAdminUserProfilesRequest]) (*connect_go.Response[v1.SearchAdminUserProfilesResponse], error)
	UpdateAdminUserProfile(context.Context, *connect_go.Request[v1.UpdateAdminUserProfileRequest]) (*connect_go.Response[emptypb.Empty], error)
}

// NewUserProfileServiceClient constructs a client for the userprofile.v1.UserProfileService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewUserProfileServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) UserProfileServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &userProfileServiceClient{
		getUserProfile: connect_go.NewClient[v1.GetUserProfileRequest, v1.GetUserProfileResponse](
			httpClient,
			baseURL+"/userprofile.v1.UserProfileService/GetUserProfile",
			opts...,
		),
		updateUserProfile: connect_go.NewClient[v1.UpdateUserProfileRequest, emptypb.Empty](
			httpClient,
			baseURL+"/userprofile.v1.UserProfileService/UpdateUserProfile",
			opts...,
		),
		getOwnUserProfile: connect_go.NewClient[emptypb.Empty, v1.GetOwnUserProfileResponse](
			httpClient,
			baseURL+"/userprofile.v1.UserProfileService/GetOwnUserProfile",
			opts...,
		),
		getAdminUserProfile: connect_go.NewClient[v1.GetAdminUserProfileRequest, v1.GetAdminUserProfileResponse](
			httpClient,
			baseURL+"/userprofile.v1.UserProfileService/GetAdminUserProfile",
			opts...,
		),
		searchAdminUserProfiles: connect_go.NewClient[v1.SearchAdminUserProfilesRequest, v1.SearchAdminUserProfilesResponse](
			httpClient,
			baseURL+"/userprofile.v1.UserProfileService/SearchAdminUserProfiles",
			opts...,
		),
		updateAdminUserProfile: connect_go.NewClient[v1.UpdateAdminUserProfileRequest, emptypb.Empty](
			httpClient,
			baseURL+"/userprofile.v1.UserProfileService/UpdateAdminUserProfile",
			opts...,
		),
	}
}

// userProfileServiceClient implements UserProfileServiceClient.
type userProfileServiceClient struct {
	getUserProfile          *connect_go.Client[v1.GetUserProfileRequest, v1.GetUserProfileResponse]
	updateUserProfile       *connect_go.Client[v1.UpdateUserProfileRequest, emptypb.Empty]
	getOwnUserProfile       *connect_go.Client[emptypb.Empty, v1.GetOwnUserProfileResponse]
	getAdminUserProfile     *connect_go.Client[v1.GetAdminUserProfileRequest, v1.GetAdminUserProfileResponse]
	searchAdminUserProfiles *connect_go.Client[v1.SearchAdminUserProfilesRequest, v1.SearchAdminUserProfilesResponse]
	updateAdminUserProfile  *connect_go.Client[v1.UpdateAdminUserProfileRequest, emptypb.Empty]
}

// GetUserProfile calls userprofile.v1.UserProfileService.GetUserProfile.
func (c *userProfileServiceClient) GetUserProfile(ctx context.Context, req *connect_go.Request[v1.GetUserProfileRequest]) (*connect_go.Response[v1.GetUserProfileResponse], error) {
	return c.getUserProfile.CallUnary(ctx, req)
}

// UpdateUserProfile calls userprofile.v1.UserProfileService.UpdateUserProfile.
func (c *userProfileServiceClient) UpdateUserProfile(ctx context.Context, req *connect_go.Request[v1.UpdateUserProfileRequest]) (*connect_go.Response[emptypb.Empty], error) {
	return c.updateUserProfile.CallUnary(ctx, req)
}

// GetOwnUserProfile calls userprofile.v1.UserProfileService.GetOwnUserProfile.
func (c *userProfileServiceClient) GetOwnUserProfile(ctx context.Context, req *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetOwnUserProfileResponse], error) {
	return c.getOwnUserProfile.CallUnary(ctx, req)
}

// GetAdminUserProfile calls userprofile.v1.UserProfileService.GetAdminUserProfile.
func (c *userProfileServiceClient) GetAdminUserProfile(ctx context.Context, req *connect_go.Request[v1.GetAdminUserProfileRequest]) (*connect_go.Response[v1.GetAdminUserProfileResponse], error) {
	return c.getAdminUserProfile.CallUnary(ctx, req)
}

// SearchAdminUserProfiles calls userprofile.v1.UserProfileService.SearchAdminUserProfiles.
func (c *userProfileServiceClient) SearchAdminUserProfiles(ctx context.Context, req *connect_go.Request[v1.SearchAdminUserProfilesRequest]) (*connect_go.Response[v1.SearchAdminUserProfilesResponse], error) {
	return c.searchAdminUserProfiles.CallUnary(ctx, req)
}

// UpdateAdminUserProfile calls userprofile.v1.UserProfileService.UpdateAdminUserProfile.
func (c *userProfileServiceClient) UpdateAdminUserProfile(ctx context.Context, req *connect_go.Request[v1.UpdateAdminUserProfileRequest]) (*connect_go.Response[emptypb.Empty], error) {
	return c.updateAdminUserProfile.CallUnary(ctx, req)
}

// UserProfileServiceHandler is an implementation of the userprofile.v1.UserProfileService service.
type UserProfileServiceHandler interface {
	GetUserProfile(context.Context, *connect_go.Request[v1.GetUserProfileRequest]) (*connect_go.Response[v1.GetUserProfileResponse], error)
	UpdateUserProfile(context.Context, *connect_go.Request[v1.UpdateUserProfileRequest]) (*connect_go.Response[emptypb.Empty], error)
	GetOwnUserProfile(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetOwnUserProfileResponse], error)
	GetAdminUserProfile(context.Context, *connect_go.Request[v1.GetAdminUserProfileRequest]) (*connect_go.Response[v1.GetAdminUserProfileResponse], error)
	SearchAdminUserProfiles(context.Context, *connect_go.Request[v1.SearchAdminUserProfilesRequest]) (*connect_go.Response[v1.SearchAdminUserProfilesResponse], error)
	UpdateAdminUserProfile(context.Context, *connect_go.Request[v1.UpdateAdminUserProfileRequest]) (*connect_go.Response[emptypb.Empty], error)
}

// NewUserProfileServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewUserProfileServiceHandler(svc UserProfileServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	mux := http.NewServeMux()
	mux.Handle("/userprofile.v1.UserProfileService/GetUserProfile", connect_go.NewUnaryHandler(
		"/userprofile.v1.UserProfileService/GetUserProfile",
		svc.GetUserProfile,
		opts...,
	))
	mux.Handle("/userprofile.v1.UserProfileService/UpdateUserProfile", connect_go.NewUnaryHandler(
		"/userprofile.v1.UserProfileService/UpdateUserProfile",
		svc.UpdateUserProfile,
		opts...,
	))
	mux.Handle("/userprofile.v1.UserProfileService/GetOwnUserProfile", connect_go.NewUnaryHandler(
		"/userprofile.v1.UserProfileService/GetOwnUserProfile",
		svc.GetOwnUserProfile,
		opts...,
	))
	mux.Handle("/userprofile.v1.UserProfileService/GetAdminUserProfile", connect_go.NewUnaryHandler(
		"/userprofile.v1.UserProfileService/GetAdminUserProfile",
		svc.GetAdminUserProfile,
		opts...,
	))
	mux.Handle("/userprofile.v1.UserProfileService/SearchAdminUserProfiles", connect_go.NewUnaryHandler(
		"/userprofile.v1.UserProfileService/SearchAdminUserProfiles",
		svc.SearchAdminUserProfiles,
		opts...,
	))
	mux.Handle("/userprofile.v1.UserProfileService/UpdateAdminUserProfile", connect_go.NewUnaryHandler(
		"/userprofile.v1.UserProfileService/UpdateAdminUserProfile",
		svc.UpdateAdminUserProfile,
		opts...,
	))
	return "/userprofile.v1.UserProfileService/", mux
}

// UnimplementedUserProfileServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedUserProfileServiceHandler struct{}

func (UnimplementedUserProfileServiceHandler) GetUserProfile(context.Context, *connect_go.Request[v1.GetUserProfileRequest]) (*connect_go.Response[v1.GetUserProfileResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("userprofile.v1.UserProfileService.GetUserProfile is not implemented"))
}

func (UnimplementedUserProfileServiceHandler) UpdateUserProfile(context.Context, *connect_go.Request[v1.UpdateUserProfileRequest]) (*connect_go.Response[emptypb.Empty], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("userprofile.v1.UserProfileService.UpdateUserProfile is not implemented"))
}

func (UnimplementedUserProfileServiceHandler) GetOwnUserProfile(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetOwnUserProfileResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("userprofile.v1.UserProfileService.GetOwnUserProfile is not implemented"))
}

func (UnimplementedUserProfileServiceHandler) GetAdminUserProfile(context.Context, *connect_go.Request[v1.GetAdminUserProfileRequest]) (*connect_go.Response[v1.GetAdminUserProfileResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("userprofile.v1.UserProfileService.GetAdminUserProfile is not implemented"))
}

func (UnimplementedUserProfileServiceHandler) SearchAdminUserProfiles(context.Context, *connect_go.Request[v1.SearchAdminUserProfilesRequest]) (*connect_go.Response[v1.SearchAdminUserProfilesResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("userprofile.v1.UserProfileService.SearchAdminUserProfiles is not implemented"))
}

func (UnimplementedUserProfileServiceHandler) UpdateAdminUserProfile(context.Context, *connect_go.Request[v1.UpdateAdminUserProfileRequest]) (*connect_go.Response[emptypb.Empty], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("userprofile.v1.UserProfileService.UpdateAdminUserProfile is not implemented"))
}
