// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: profile/v1/profile.proto

package profilev1connect

import (
	context "context"
	errors "errors"
	v1 "github.com/10kn/wink_common/server/profile/v1"
	connect_go "github.com/bufbuild/connect-go"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// ProfileServiceName is the fully-qualified name of the ProfileService service.
	ProfileServiceName = "profile.v1.ProfileService"
)

// ProfileServiceClient is a client for the profile.v1.ProfileService service.
type ProfileServiceClient interface {
	GetGenders(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetGendersResponse], error)
	GetPrefectures(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetPrefecturesResponse], error)
	GetCities(context.Context, *connect_go.Request[v1.GetCitiesRequest]) (*connect_go.Response[v1.GetCitiesResponse], error)
	GetJobs(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetJobsResponse], error)
	GetAlcohols(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetAlcoholsResponse], error)
	GetAnnualIncomes(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetAnnualIncomesResponse], error)
	GetBloodTypes(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetBloodTypesResponse], error)
	GetCigarettes(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetCigarettesResponse], error)
	GetDateCosts(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetDateCostsResponse], error)
	GetEducationalBackgrounds(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetEducationalBackgroundsResponse], error)
	GetHolidays(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetHolidaysResponse], error)
	GetHousemates(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetHousematesResponse], error)
	GetShapes(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetShapesResponse], error)
	GetPersonalities(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetPersonalitiesResponse], error)
	GetHobbies(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetHobbiesResponse], error)
	GetPlanCategories(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetPlanCategoriesResponse], error)
}

// NewProfileServiceClient constructs a client for the profile.v1.ProfileService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewProfileServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) ProfileServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &profileServiceClient{
		getGenders: connect_go.NewClient[emptypb.Empty, v1.GetGendersResponse](
			httpClient,
			baseURL+"/profile.v1.ProfileService/GetGenders",
			opts...,
		),
		getPrefectures: connect_go.NewClient[emptypb.Empty, v1.GetPrefecturesResponse](
			httpClient,
			baseURL+"/profile.v1.ProfileService/GetPrefectures",
			opts...,
		),
		getCities: connect_go.NewClient[v1.GetCitiesRequest, v1.GetCitiesResponse](
			httpClient,
			baseURL+"/profile.v1.ProfileService/GetCities",
			opts...,
		),
		getJobs: connect_go.NewClient[emptypb.Empty, v1.GetJobsResponse](
			httpClient,
			baseURL+"/profile.v1.ProfileService/GetJobs",
			opts...,
		),
		getAlcohols: connect_go.NewClient[emptypb.Empty, v1.GetAlcoholsResponse](
			httpClient,
			baseURL+"/profile.v1.ProfileService/GetAlcohols",
			opts...,
		),
		getAnnualIncomes: connect_go.NewClient[emptypb.Empty, v1.GetAnnualIncomesResponse](
			httpClient,
			baseURL+"/profile.v1.ProfileService/GetAnnualIncomes",
			opts...,
		),
		getBloodTypes: connect_go.NewClient[emptypb.Empty, v1.GetBloodTypesResponse](
			httpClient,
			baseURL+"/profile.v1.ProfileService/GetBloodTypes",
			opts...,
		),
		getCigarettes: connect_go.NewClient[emptypb.Empty, v1.GetCigarettesResponse](
			httpClient,
			baseURL+"/profile.v1.ProfileService/GetCigarettes",
			opts...,
		),
		getDateCosts: connect_go.NewClient[emptypb.Empty, v1.GetDateCostsResponse](
			httpClient,
			baseURL+"/profile.v1.ProfileService/GetDateCosts",
			opts...,
		),
		getEducationalBackgrounds: connect_go.NewClient[emptypb.Empty, v1.GetEducationalBackgroundsResponse](
			httpClient,
			baseURL+"/profile.v1.ProfileService/GetEducationalBackgrounds",
			opts...,
		),
		getHolidays: connect_go.NewClient[emptypb.Empty, v1.GetHolidaysResponse](
			httpClient,
			baseURL+"/profile.v1.ProfileService/GetHolidays",
			opts...,
		),
		getHousemates: connect_go.NewClient[emptypb.Empty, v1.GetHousematesResponse](
			httpClient,
			baseURL+"/profile.v1.ProfileService/GetHousemates",
			opts...,
		),
		getShapes: connect_go.NewClient[emptypb.Empty, v1.GetShapesResponse](
			httpClient,
			baseURL+"/profile.v1.ProfileService/GetShapes",
			opts...,
		),
		getPersonalities: connect_go.NewClient[emptypb.Empty, v1.GetPersonalitiesResponse](
			httpClient,
			baseURL+"/profile.v1.ProfileService/GetPersonalities",
			opts...,
		),
		getHobbies: connect_go.NewClient[emptypb.Empty, v1.GetHobbiesResponse](
			httpClient,
			baseURL+"/profile.v1.ProfileService/GetHobbies",
			opts...,
		),
		getPlanCategories: connect_go.NewClient[emptypb.Empty, v1.GetPlanCategoriesResponse](
			httpClient,
			baseURL+"/profile.v1.ProfileService/GetPlanCategories",
			opts...,
		),
	}
}

// profileServiceClient implements ProfileServiceClient.
type profileServiceClient struct {
	getGenders                *connect_go.Client[emptypb.Empty, v1.GetGendersResponse]
	getPrefectures            *connect_go.Client[emptypb.Empty, v1.GetPrefecturesResponse]
	getCities                 *connect_go.Client[v1.GetCitiesRequest, v1.GetCitiesResponse]
	getJobs                   *connect_go.Client[emptypb.Empty, v1.GetJobsResponse]
	getAlcohols               *connect_go.Client[emptypb.Empty, v1.GetAlcoholsResponse]
	getAnnualIncomes          *connect_go.Client[emptypb.Empty, v1.GetAnnualIncomesResponse]
	getBloodTypes             *connect_go.Client[emptypb.Empty, v1.GetBloodTypesResponse]
	getCigarettes             *connect_go.Client[emptypb.Empty, v1.GetCigarettesResponse]
	getDateCosts              *connect_go.Client[emptypb.Empty, v1.GetDateCostsResponse]
	getEducationalBackgrounds *connect_go.Client[emptypb.Empty, v1.GetEducationalBackgroundsResponse]
	getHolidays               *connect_go.Client[emptypb.Empty, v1.GetHolidaysResponse]
	getHousemates             *connect_go.Client[emptypb.Empty, v1.GetHousematesResponse]
	getShapes                 *connect_go.Client[emptypb.Empty, v1.GetShapesResponse]
	getPersonalities          *connect_go.Client[emptypb.Empty, v1.GetPersonalitiesResponse]
	getHobbies                *connect_go.Client[emptypb.Empty, v1.GetHobbiesResponse]
	getPlanCategories         *connect_go.Client[emptypb.Empty, v1.GetPlanCategoriesResponse]
}

// GetGenders calls profile.v1.ProfileService.GetGenders.
func (c *profileServiceClient) GetGenders(ctx context.Context, req *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetGendersResponse], error) {
	return c.getGenders.CallUnary(ctx, req)
}

// GetPrefectures calls profile.v1.ProfileService.GetPrefectures.
func (c *profileServiceClient) GetPrefectures(ctx context.Context, req *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetPrefecturesResponse], error) {
	return c.getPrefectures.CallUnary(ctx, req)
}

// GetCities calls profile.v1.ProfileService.GetCities.
func (c *profileServiceClient) GetCities(ctx context.Context, req *connect_go.Request[v1.GetCitiesRequest]) (*connect_go.Response[v1.GetCitiesResponse], error) {
	return c.getCities.CallUnary(ctx, req)
}

// GetJobs calls profile.v1.ProfileService.GetJobs.
func (c *profileServiceClient) GetJobs(ctx context.Context, req *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetJobsResponse], error) {
	return c.getJobs.CallUnary(ctx, req)
}

// GetAlcohols calls profile.v1.ProfileService.GetAlcohols.
func (c *profileServiceClient) GetAlcohols(ctx context.Context, req *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetAlcoholsResponse], error) {
	return c.getAlcohols.CallUnary(ctx, req)
}

// GetAnnualIncomes calls profile.v1.ProfileService.GetAnnualIncomes.
func (c *profileServiceClient) GetAnnualIncomes(ctx context.Context, req *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetAnnualIncomesResponse], error) {
	return c.getAnnualIncomes.CallUnary(ctx, req)
}

// GetBloodTypes calls profile.v1.ProfileService.GetBloodTypes.
func (c *profileServiceClient) GetBloodTypes(ctx context.Context, req *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetBloodTypesResponse], error) {
	return c.getBloodTypes.CallUnary(ctx, req)
}

// GetCigarettes calls profile.v1.ProfileService.GetCigarettes.
func (c *profileServiceClient) GetCigarettes(ctx context.Context, req *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetCigarettesResponse], error) {
	return c.getCigarettes.CallUnary(ctx, req)
}

// GetDateCosts calls profile.v1.ProfileService.GetDateCosts.
func (c *profileServiceClient) GetDateCosts(ctx context.Context, req *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetDateCostsResponse], error) {
	return c.getDateCosts.CallUnary(ctx, req)
}

// GetEducationalBackgrounds calls profile.v1.ProfileService.GetEducationalBackgrounds.
func (c *profileServiceClient) GetEducationalBackgrounds(ctx context.Context, req *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetEducationalBackgroundsResponse], error) {
	return c.getEducationalBackgrounds.CallUnary(ctx, req)
}

// GetHolidays calls profile.v1.ProfileService.GetHolidays.
func (c *profileServiceClient) GetHolidays(ctx context.Context, req *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetHolidaysResponse], error) {
	return c.getHolidays.CallUnary(ctx, req)
}

// GetHousemates calls profile.v1.ProfileService.GetHousemates.
func (c *profileServiceClient) GetHousemates(ctx context.Context, req *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetHousematesResponse], error) {
	return c.getHousemates.CallUnary(ctx, req)
}

// GetShapes calls profile.v1.ProfileService.GetShapes.
func (c *profileServiceClient) GetShapes(ctx context.Context, req *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetShapesResponse], error) {
	return c.getShapes.CallUnary(ctx, req)
}

// GetPersonalities calls profile.v1.ProfileService.GetPersonalities.
func (c *profileServiceClient) GetPersonalities(ctx context.Context, req *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetPersonalitiesResponse], error) {
	return c.getPersonalities.CallUnary(ctx, req)
}

// GetHobbies calls profile.v1.ProfileService.GetHobbies.
func (c *profileServiceClient) GetHobbies(ctx context.Context, req *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetHobbiesResponse], error) {
	return c.getHobbies.CallUnary(ctx, req)
}

// GetPlanCategories calls profile.v1.ProfileService.GetPlanCategories.
func (c *profileServiceClient) GetPlanCategories(ctx context.Context, req *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetPlanCategoriesResponse], error) {
	return c.getPlanCategories.CallUnary(ctx, req)
}

// ProfileServiceHandler is an implementation of the profile.v1.ProfileService service.
type ProfileServiceHandler interface {
	GetGenders(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetGendersResponse], error)
	GetPrefectures(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetPrefecturesResponse], error)
	GetCities(context.Context, *connect_go.Request[v1.GetCitiesRequest]) (*connect_go.Response[v1.GetCitiesResponse], error)
	GetJobs(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetJobsResponse], error)
	GetAlcohols(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetAlcoholsResponse], error)
	GetAnnualIncomes(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetAnnualIncomesResponse], error)
	GetBloodTypes(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetBloodTypesResponse], error)
	GetCigarettes(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetCigarettesResponse], error)
	GetDateCosts(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetDateCostsResponse], error)
	GetEducationalBackgrounds(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetEducationalBackgroundsResponse], error)
	GetHolidays(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetHolidaysResponse], error)
	GetHousemates(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetHousematesResponse], error)
	GetShapes(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetShapesResponse], error)
	GetPersonalities(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetPersonalitiesResponse], error)
	GetHobbies(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetHobbiesResponse], error)
	GetPlanCategories(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetPlanCategoriesResponse], error)
}

// NewProfileServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewProfileServiceHandler(svc ProfileServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	mux := http.NewServeMux()
	mux.Handle("/profile.v1.ProfileService/GetGenders", connect_go.NewUnaryHandler(
		"/profile.v1.ProfileService/GetGenders",
		svc.GetGenders,
		opts...,
	))
	mux.Handle("/profile.v1.ProfileService/GetPrefectures", connect_go.NewUnaryHandler(
		"/profile.v1.ProfileService/GetPrefectures",
		svc.GetPrefectures,
		opts...,
	))
	mux.Handle("/profile.v1.ProfileService/GetCities", connect_go.NewUnaryHandler(
		"/profile.v1.ProfileService/GetCities",
		svc.GetCities,
		opts...,
	))
	mux.Handle("/profile.v1.ProfileService/GetJobs", connect_go.NewUnaryHandler(
		"/profile.v1.ProfileService/GetJobs",
		svc.GetJobs,
		opts...,
	))
	mux.Handle("/profile.v1.ProfileService/GetAlcohols", connect_go.NewUnaryHandler(
		"/profile.v1.ProfileService/GetAlcohols",
		svc.GetAlcohols,
		opts...,
	))
	mux.Handle("/profile.v1.ProfileService/GetAnnualIncomes", connect_go.NewUnaryHandler(
		"/profile.v1.ProfileService/GetAnnualIncomes",
		svc.GetAnnualIncomes,
		opts...,
	))
	mux.Handle("/profile.v1.ProfileService/GetBloodTypes", connect_go.NewUnaryHandler(
		"/profile.v1.ProfileService/GetBloodTypes",
		svc.GetBloodTypes,
		opts...,
	))
	mux.Handle("/profile.v1.ProfileService/GetCigarettes", connect_go.NewUnaryHandler(
		"/profile.v1.ProfileService/GetCigarettes",
		svc.GetCigarettes,
		opts...,
	))
	mux.Handle("/profile.v1.ProfileService/GetDateCosts", connect_go.NewUnaryHandler(
		"/profile.v1.ProfileService/GetDateCosts",
		svc.GetDateCosts,
		opts...,
	))
	mux.Handle("/profile.v1.ProfileService/GetEducationalBackgrounds", connect_go.NewUnaryHandler(
		"/profile.v1.ProfileService/GetEducationalBackgrounds",
		svc.GetEducationalBackgrounds,
		opts...,
	))
	mux.Handle("/profile.v1.ProfileService/GetHolidays", connect_go.NewUnaryHandler(
		"/profile.v1.ProfileService/GetHolidays",
		svc.GetHolidays,
		opts...,
	))
	mux.Handle("/profile.v1.ProfileService/GetHousemates", connect_go.NewUnaryHandler(
		"/profile.v1.ProfileService/GetHousemates",
		svc.GetHousemates,
		opts...,
	))
	mux.Handle("/profile.v1.ProfileService/GetShapes", connect_go.NewUnaryHandler(
		"/profile.v1.ProfileService/GetShapes",
		svc.GetShapes,
		opts...,
	))
	mux.Handle("/profile.v1.ProfileService/GetPersonalities", connect_go.NewUnaryHandler(
		"/profile.v1.ProfileService/GetPersonalities",
		svc.GetPersonalities,
		opts...,
	))
	mux.Handle("/profile.v1.ProfileService/GetHobbies", connect_go.NewUnaryHandler(
		"/profile.v1.ProfileService/GetHobbies",
		svc.GetHobbies,
		opts...,
	))
	mux.Handle("/profile.v1.ProfileService/GetPlanCategories", connect_go.NewUnaryHandler(
		"/profile.v1.ProfileService/GetPlanCategories",
		svc.GetPlanCategories,
		opts...,
	))
	return "/profile.v1.ProfileService/", mux
}

// UnimplementedProfileServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedProfileServiceHandler struct{}

func (UnimplementedProfileServiceHandler) GetGenders(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetGendersResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("profile.v1.ProfileService.GetGenders is not implemented"))
}

func (UnimplementedProfileServiceHandler) GetPrefectures(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetPrefecturesResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("profile.v1.ProfileService.GetPrefectures is not implemented"))
}

func (UnimplementedProfileServiceHandler) GetCities(context.Context, *connect_go.Request[v1.GetCitiesRequest]) (*connect_go.Response[v1.GetCitiesResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("profile.v1.ProfileService.GetCities is not implemented"))
}

func (UnimplementedProfileServiceHandler) GetJobs(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetJobsResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("profile.v1.ProfileService.GetJobs is not implemented"))
}

func (UnimplementedProfileServiceHandler) GetAlcohols(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetAlcoholsResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("profile.v1.ProfileService.GetAlcohols is not implemented"))
}

func (UnimplementedProfileServiceHandler) GetAnnualIncomes(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetAnnualIncomesResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("profile.v1.ProfileService.GetAnnualIncomes is not implemented"))
}

func (UnimplementedProfileServiceHandler) GetBloodTypes(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetBloodTypesResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("profile.v1.ProfileService.GetBloodTypes is not implemented"))
}

func (UnimplementedProfileServiceHandler) GetCigarettes(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetCigarettesResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("profile.v1.ProfileService.GetCigarettes is not implemented"))
}

func (UnimplementedProfileServiceHandler) GetDateCosts(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetDateCostsResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("profile.v1.ProfileService.GetDateCosts is not implemented"))
}

func (UnimplementedProfileServiceHandler) GetEducationalBackgrounds(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetEducationalBackgroundsResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("profile.v1.ProfileService.GetEducationalBackgrounds is not implemented"))
}

func (UnimplementedProfileServiceHandler) GetHolidays(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetHolidaysResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("profile.v1.ProfileService.GetHolidays is not implemented"))
}

func (UnimplementedProfileServiceHandler) GetHousemates(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetHousematesResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("profile.v1.ProfileService.GetHousemates is not implemented"))
}

func (UnimplementedProfileServiceHandler) GetShapes(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetShapesResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("profile.v1.ProfileService.GetShapes is not implemented"))
}

func (UnimplementedProfileServiceHandler) GetPersonalities(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetPersonalitiesResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("profile.v1.ProfileService.GetPersonalities is not implemented"))
}

func (UnimplementedProfileServiceHandler) GetHobbies(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetHobbiesResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("profile.v1.ProfileService.GetHobbies is not implemented"))
}

func (UnimplementedProfileServiceHandler) GetPlanCategories(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetPlanCategoriesResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("profile.v1.ProfileService.GetPlanCategories is not implemented"))
}
